application: nominate-jeremy
version: 2
runtime: python27
threadsafe: true
api_version: 1

builtins:
- deferred: on
- remote_api: on
- admin_redirect: on

libraries:
- name: jinja2
  version: 2.6
- name: webapp2
  version: 2.5.1

handlers:
# Handlers for the Write to MP functions
# (Copy these to the app.yaml file in your application, if you are
# integrating this code with an existing app engine application.)
- url: /mp/(write|letter-sent)
  script: mp.handlers.app
- url: /(mp/images/.+)
  static_files: \1
  upload: mp/images/.+
- url: /mp/.+
  login: admin
  script: mp.handlers.app

# Static files
#   /styles maps to the styles directory
- url: /styles/(.+)
  static_files: styles/\1
  upload: styles/.+
#  /lib maps to the jslib directory
- url: /lib/(.+)
  static_files: jslib/\1
  upload: jslib/.+

# Favicon
- url: /favicon.ico
  script: mp.handlers.app
